###############################################
# USERS SERVICE VALUES
# These values override deployment templates
###############################################

replicaCount: 2

image:
  repository: "<AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-users"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5001

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

db:
  host: "<users_db_endpoint_from_terraform>"
  name: "usersdb"
  user: "users_admin"
  password: "UsersDB@12345"

jwtSecret: "ThisIsASecretKey"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
